//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueSharp.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeagueSharp.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;yasuo&quot;: &quot;\u75be\u98ce\u5251\u8c6a&quot;,
        ///    &quot;velkoz&quot;: &quot;\u865a\u7a7a\u4e4b\u773c&quot;,
        ///    &quot;braum&quot;: &quot;\u5f17\u96f7\u5c14\u5353\u5fb7\u4e4b\u5fc3&quot;,
        ///    &quot;gnar&quot;: &quot;\u8ff7\u5931\u4e4b\u7259&quot;,
        ///    &quot;azir&quot;: &quot;\u6c99\u6f20\u7687\u5e1d&quot;,
        ///    &quot;kalista&quot;: &quot;\u590d\u4ec7\u4e4b\u77db&quot;,
        ///    &quot;rekSai&quot;: &quot;\u865a\u7a7a\u9041\u5730\u517d&quot;,
        ///    &quot;bard&quot;: &quot;\u661f\u754c\u6e38\u795e&quot;,
        ///    &quot;ekko&quot;: &quot;\u65f6\u95f4\u523a\u5ba2&quot;,	
        ///    &quot;aatrox&quot;: &quot;\u6697\u88d4\u5251\u9b54&quot;,
        ///    &quot;ahri&quot;: &quot;\u4e5d\u5c3e\u5996\u72d0&quot;,
        ///    &quot;akali&quot;: &quot;\u6697\u5f71\u4e4b\u [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ChineseJson {
            get {
                return ResourceManager.GetString("ChineseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CPActiveSlider {
            get {
                object obj = ResourceManager.GetObject("CPActiveSlider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CPForm {
            get {
                object obj = ResourceManager.GetObject("CPForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CPInactiveSlider {
            get {
                object obj = ResourceManager.GetObject("CPInactiveSlider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
